name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Hiermee kan je de workflow handmatig starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: HerexamenYannickMarijnissen  # Zorg ervoor dat deze directory correct is

      - name: Build
        run: dotnet build --configuration Release
        working-directory: HerexamenYannickMarijnissen  # Zorg ervoor dat deze directory correct is

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: HerexamenYannickMarijnissen  # Zorg ervoor dat deze directory correct is

      - name: List files in publish directory
        run: ls -R HerexamenYannickMarijnissen/publish
        working-directory: HerexamenYannickMarijnissen  # Zorg ervoor dat deze directory correct is

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'HerexamenYannickMarijnissen'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'HerexamenYannickMarijnissen/publish'  # Zorg ervoor dat dit pad correct is
