name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Hiermee kan je de workflow handmatig starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update naar de nieuwste versie

      - name: Setup .NET
        uses: actions/setup-dotnet@v4  # Update naar de nieuwste versie
        with:
          dotnet-version: '6.0' # Zorg ervoor dat dit overeenkomt met jouw .NET versie

      - name: Restore dependencies
        run: dotnet restore
        working-directory: bordspel/HerexamenYannickMarijnissen  # Specificeer de juiste werkdirectory

      - name: Build
        run: dotnet build --configuration Release
        working-directory: bordspel/HerexamenYannickMarijnissen  # Specificeer de juiste werkdirectory

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: bordspel/HerexamenYannickMarijnissen  # Specificeer de juiste werkdirectory

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'HerexamenYannickMarijnissen'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
